# Generated by Django 3.2.4 on 2022-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='webcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=20)),
                ('cardpic', models.ImageField(default='', upload_to='static/images/')),
                ('cardlink', models.CharField(max_length=500)),
            ],
        ),
    ]
