# Generated by Django 3.2.4 on 2022-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0002_webcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcard',
            name='cardname',
            field=models.CharField(max_length=50),
        ),
    ]
