# Generated by Django 3.2.4 on 2022-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0003_alter_webcard_cardname'),
    ]

    operations = [
        migrations.CreateModel(
            name='youTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(default='', upload_to='static/images/')),
                ('vtitle', models.CharField(max_length=100)),
                ('vdiscription', models.CharField(max_length=500)),
                ('vchannel', models.CharField(max_length=50)),
                ('vuploaded', models.CharField(max_length=50)),
                ('vlink', models.CharField(max_length=500)),
            ],
        ),
    ]
