# Generated by Django 3.2.4 on 2022-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0004_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
