# Generated by Django 3.2.4 on 2022-05-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0005_alter_youtube_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='freeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeicon', models.ImageField(default='', upload_to='static/images/')),
                ('freetitle', models.CharField(max_length=30)),
                ('freelink', models.CharField(max_length=500)),
            ],
        ),
    ]
