# Generated by Django 4.0.4 on 2022-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0007_videogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_img', models.ImageField(default='', upload_to='static/images/')),
                ('os_title', models.CharField(max_length=30)),
                ('os_discription', models.CharField(max_length=100)),
                ('os_moreinfo', models.CharField(max_length=200)),
                ('os_download', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='videoGallery',
        ),
    ]
