# Generated by Django 4.0.4 on 2022-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0008_os_delete_videogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='os1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_img1', models.ImageField(default='', upload_to='static/images/')),
                ('os_title1', models.CharField(max_length=30)),
                ('os_discription1', models.CharField(max_length=100)),
                ('os_moreinfo1', models.CharField(max_length=200)),
                ('os_download1', models.CharField(max_length=500)),
            ],
        ),
    ]
