# Generated by Django 4.0.4 on 2022-05-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0012_alter_resume_my_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='newscard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsname', models.CharField(max_length=80)),
                ('newspic', models.ImageField(default='', upload_to='static/images/')),
                ('newslink', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='newscard1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsname1', models.CharField(max_length=80)),
                ('newspic1', models.ImageField(default='', upload_to='static/images/')),
                ('newslink1', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='newscard2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsname2', models.CharField(max_length=80)),
                ('newspic2', models.ImageField(default='', upload_to='static/images/')),
                ('newslink2', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='newscard3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsname3', models.CharField(max_length=80)),
                ('newspic3', models.ImageField(default='', upload_to='static/images/')),
                ('newslink3', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='newscard4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsname4', models.CharField(max_length=80)),
                ('newspic4', models.ImageField(default='', upload_to='static/images/')),
                ('newslink4', models.CharField(max_length=500)),
            ],
        ),
    ]
