# Generated by Django 4.0 on 2022-05-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixDoc', '0013_newscard_newscard1_newscard2_newscard3_newscard4'),
    ]

    operations = [
        migrations.CreateModel(
            name='templateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_pic', models.ImageField(default='', upload_to='static/images/')),
                ('temp_download', models.FileField(blank=True, upload_to='static/doc/')),
            ],
        ),
    ]
